---
title: "Geographies enrichment"
toc: true
format:
  html: 
    code-fold: true
    theme: simplex
---

# 0) Load packages and data

```{r}
pacman::p_load(tidyverse, here, janitor, sf, skimr, exactextractr, raster, terra)

sf::sf_use_s2(FALSE) # This is needed because the HydroBASINS data has some geometries issues
```

**Load data**

```{r, warning=FALSE, message=FALSE, results='hide'}
geo_summary <- read_rds(here("output", "summarise_geo", "1_summarise", "hybas6_summary.rds"))

vcp <- rast(here("input", "raster_value_crop_prod", "spam2010V2r0_global_V_agg_VP_CROP_A.tif"))

rfs <- brick(here("input", "rfs_data", "rfs_data.tif"))

names(rfs) <- c("RC1", "RC2", "RC3", "S2_4", "RC8", "Phy_P3rc")

country_adm1 <- st_read(here("input", "geographies", "world_adm1_esri_edited_diss.shp"))

wmo <- st_read(here("input", "geographies", "wmobb_basins.shp"))
```

# 1) Extract value of production (MapSpam)

```{r}
ext_vcp <- function(geo){
  
  vcp_geo <- exact_extract(vcp, geo, fun = "mean", append_cols = 1)

  geo %>% 
    dplyr::select(1) %>%
    left_join(vcp_geo) %>%
    dplyr::select(1, vcp_mean = mean) %>%
    st_drop_geometry()
}
```

# 2) Extract Risk Filter scores

```{r}
ext_rfs <- function(geo){
  
  rfs_geo <- exact_extract(rfs, geo, fun = "mean", append_cols = 1)

  geo %>% 
    dplyr::select(1) %>%
    left_join(rfs_geo) %>%
    dplyr::select(
      1,
      RC1 = mean.RC1,
      RC2 = mean.RC2,
      RC3 = mean.RC3,
      S2_4 = mean.S2_4,
      RC8 = mean.RC8,
      Phy_P3rc = mean.Phy_P3rc
    ) %>%
    st_drop_geometry()
}
```

# 3) Apply functions to geography

```{r}
enrich_geo <- function(geo){
  
  geo %>%
    left_join(ext_vcp(geo)) %>%
    left_join(ext_rfs(geo)) %>%
    mutate(across(where(is.double), ~ round(., 2))) %>%
    mutate(d_sites = round(n_sites/area_km2, 6)) %>%
    st_join(dplyr::select(country_adm1, country = COUNTRY, adm1 = NAME), largest = TRUE) %>%
    st_join(dplyr::select(wmo, wmobb_id = WMOBB, wmo_basin = WMOBBName), largest = TRUE) %>%
    relocate(country:wmo_basin, .after = region)
}
```

```{r}  
geo_enriched <- enrich_geo(geo_summary)
```

```{r}
geo_enriched %>% 
  st_drop_geometry() %>%
  skim()
```

# 4) Export files

```{r}
write_rds(geo_enriched, here("output", "summarise_geo", "2_enrichment", "hybas6_enriched.rds"))
```
